# Generated by Django 3.0.6 on 2020-06-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clinic')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Donor')),
            ],
        ),
    ]
