# Generated by Django 3.0.7 on 2020-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField(null=True)),
                ('clinic_id', models.IntegerField(null=True)),
                ('appointment_time', models.DateTimeField(null=True)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
