# Generated by Django 3.0.7 on 2020-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='donor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='donor_id',
            field=models.IntegerField(null=True),
        ),
    ]
