# Generated by Django 3.0.7 on 2020-06-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='appointment_with',
            field=models.ManyToManyField(related_name='appointments', to='users.Clinic'),
        ),
    ]
