# Generated by Django 3.0.7 on 2020-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200608_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='users.Donor'),
        ),
    ]
